// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace LetsDoStuff.Domain.Migrations
{
    public partial class RemoveActivityTagLinkEntitty : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ActivityTag_Activities_ActivityId",
                table: "ActivityTag");

            migrationBuilder.DropForeignKey(
                name: "FK_ActivityTag_Activities_ActivityId1",
                table: "ActivityTag");

            migrationBuilder.DropForeignKey(
                name: "FK_ActivityTag_Tags_TagId",
                table: "ActivityTag");

            migrationBuilder.DropForeignKey(
                name: "FK_ActivityTag_Tags_TagId1",
                table: "ActivityTag");

            migrationBuilder.DropIndex(
                name: "IX_ActivityTag_ActivityId1",
                table: "ActivityTag");

            migrationBuilder.DropIndex(
                name: "IX_ActivityTag_TagId1",
                table: "ActivityTag");

            migrationBuilder.DropColumn(
                name: "ActivityId1",
                table: "ActivityTag");

            migrationBuilder.DropColumn(
                name: "TagId1",
                table: "ActivityTag");

            migrationBuilder.RenameColumn(
                name: "TagId",
                table: "ActivityTag",
                newName: "TagsId");

            migrationBuilder.RenameColumn(
                name: "ActivityId",
                table: "ActivityTag",
                newName: "ActivitiesId");

            migrationBuilder.RenameIndex(
                name: "IX_ActivityTag_TagId",
                table: "ActivityTag",
                newName: "IX_ActivityTag_TagsId");

            migrationBuilder.AddForeignKey(
                name: "FK_ActivityTag_Activities_ActivitiesId",
                table: "ActivityTag",
                column: "ActivitiesId",
                principalTable: "Activities",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_ActivityTag_Tags_TagsId",
                table: "ActivityTag",
                column: "TagsId",
                principalTable: "Tags",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ActivityTag_Activities_ActivitiesId",
                table: "ActivityTag");

            migrationBuilder.DropForeignKey(
                name: "FK_ActivityTag_Tags_TagsId",
                table: "ActivityTag");

            migrationBuilder.RenameColumn(
                name: "TagsId",
                table: "ActivityTag",
                newName: "TagId");

            migrationBuilder.RenameColumn(
                name: "ActivitiesId",
                table: "ActivityTag",
                newName: "ActivityId");

            migrationBuilder.RenameIndex(
                name: "IX_ActivityTag_TagsId",
                table: "ActivityTag",
                newName: "IX_ActivityTag_TagId");

            migrationBuilder.AddColumn<int>(
                name: "ActivityId1",
                table: "ActivityTag",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "TagId1",
                table: "ActivityTag",
                type: "int",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_ActivityTag_ActivityId1",
                table: "ActivityTag",
                column: "ActivityId1");

            migrationBuilder.CreateIndex(
                name: "IX_ActivityTag_TagId1",
                table: "ActivityTag",
                column: "TagId1");

            migrationBuilder.AddForeignKey(
                name: "FK_ActivityTag_Activities_ActivityId",
                table: "ActivityTag",
                column: "ActivityId",
                principalTable: "Activities",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_ActivityTag_Activities_ActivityId1",
                table: "ActivityTag",
                column: "ActivityId1",
                principalTable: "Activities",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ActivityTag_Tags_TagId",
                table: "ActivityTag",
                column: "TagId",
                principalTable: "Tags",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_ActivityTag_Tags_TagId1",
                table: "ActivityTag",
                column: "TagId1",
                principalTable: "Tags",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
